### ISSUE TITLE
Zpětná vazba

### ISSUE THREAD

**Issue by MilaSkalova** [slavomira94/zaverecny-projekt#1]
Ahoj Slávko,

jediný bod, který chybí splnit, je responzivní verze. Kouče dělám poprvé, musím se poradit s Luďkem, zda je možné projekt uznat :-)

Míla

**Comment by slavomira94** [comment]
> Ahoj Slávko,
> 
> jediný bod, který chybí splnit, je responzivní verze. Kouče dělám poprvé, musím se poradit s Luďkem, zda je možné projekt uznat :-)
> 
> Míla

Ahoj, 

som si toho vedomá a písala som to myslím aj do komentára v Google classroom - mám to tam, ale nefunguje mi to a neviem prečo (googlila som, prechádzala videá, neprišla som na to). Zistila som to však až po konzultáciách a keďže sa blížil deadline, tak som projekt odovzdala aj tak, s tým, že snáď to stihnem opraviť (ale stále neviem, kde je chyba). Vieš ma možno popostrčiť správnym smerom, prosím?

**Comment by MilaSkalova** [comment]
Určitě se pokusím :-)

Ing. Miloslava Skalová

výchovná poradkyně
třídní učitelka T3B
odborné IT předměty

SPŠelit Dobruška
www.spselitdobruska.cz
________________________________
Od: Slavomira ***@***.***>
Odesláno: Monday, June 6, 2022 11:09:31 PM
Komu: slavomira94/zaverecny-projekt ***@***.***>
Kopie: Miloslava Skalová ***@***.***>; Author ***@***.***>
Předmět: Re: [slavomira94/zaverecny-projekt] Zpětná vazba (Issue #1)


Ahoj Slávko,

jediný bod, který chybí splnit, je responzivní verze. Kouče dělám poprvé, musím se poradit s Luďkem, zda je možné projekt uznat :-)

Míla

Ahoj,

som si toho vedomá a písala som to myslím aj do komentára v Google classroom - mám to tam, ale nefunguje mi to a neviem prečo (googlila som, prechádzala videá, neprišla som na to). Zistila som to však až po konzultáciách a keďže sa blížil deadline, tak som projekt odovzdala aj tak, s tým, že snáď to stihnem opraviť (ale stále neviem, kde je chyba). Vieš ma možno popostrčiť správnym smerom, prosím?

**Comment by slavomira94** [comment]
> Ahoj Slávko,
> 
> jediný bod, který chybí splnit, je responzivní verze. Kouče dělám poprvé, musím se poradit s Luďkem, zda je možné projekt uznat :-)
> 
> Míla

Už som na to konečne prišla. Opravené.
